name: SSH Tunnel & Forwarding
version: 0.0.3
slug: autossh
description: >-
  Permanent HA forwarding and domain linking through an SSH tunnel
url: 'https://github.com/curserio/home-assistant-addons'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
map:
  - 'config:rw'

watchdog: 'tcp://127.0.0.1:8123'

options:
  hostname: ''
  ssh_port: 22
  username: autossh
  remote_forwarding:
    - '0.0.0.0:8123:172.30.32.1:8123'
  other_ssh_options: '-v -N'
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding:
    - str
  other_ssh_options: str
